### ISSUE TITLE
无法使用，也没有生成config

### ISSUE THREAD

**Issue by cuihua0** [TISUnion/QuickBackupM#17]
Traceback (most recent call last):
  File "C:\python365\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 447, in trigger_listener
    listener.execute(self.mcdr_server.server_interface, *args)
  File "C:\python365\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\QuickBackupM_en.py", line 583, in on_load
    load_config(server)
  File "plugins\QuickBackupM_en.py", line 564, in load_config
    if info:
NameError: name 'info' is not defined
[MCDR] [12:35:20] [TaskExecutor/INFO]: Reload "quick_backup_multi@1.1.0" successfully
[MCDR] [12:35:20] [TaskExecutor/INFO]: Reloaded: 1 plugins; Active plugin amount: 2

!!qb make
[Server] [12:40:54] [Server thread/INFO]: Unknown command. Type "/help" for help.

**Comment by Fallen-Breath** [comment]
check  [v1.1.3](https://github.com/TISUnion/QuickBackupM/releases/tag/v1.1.3)

**Comment by cuihua0** [comment]
> check [v1.1.3](https://github.com/TISUnion/QuickBackupM/releases/tag/v1.1.3)

谢谢了～明天试试～～
