### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问

### ISSUE THREAD

**Issue by mouren-zhang** [TISUnion/QuickBackupM#26]
提示的是【PermissionError: [WinError 5] 拒绝访问】
已知的方法就是 将python的访问权限打开。但是我已经吧所有权限打开，还是管理员身份运行python也重装过 系统也是 包括MCDR的端都重配过，依旧无法解决。

**Comment by mouren-zhang** [comment]
好像是更改了 目前已知更改【playdata】的文件 备份回触发，没有解决具体的解决思路，现在的的解决方案是
加多一个qb槽位用于冗余，在用外部检测多出来槽位是否存在，存在即删除

**Comment by mouren-zhang** [comment]
我好像可以复现这个错误了  晚点我多试几次

**Comment by shenjackyuanjie** [comment]
等你哈（

**Comment by GenMannnnnn** [comment]
请问这个问题有解决吗?目前也遇到这个问题

**Comment by shenjackyuanjie** [comment]
> 我好像可以复现这个错误了 晚点我多试几次

所以你的试验呢？（
另外你的log呢？（

**Comment by GenMannnnnn** [comment]
目前是跳出这个报错
PermissionError: [WinError 5] 存取被拒。: 'E:\\MinecraftSERVER\\server\\mirror\\server\\world\\playerdata'

**Comment by Fallen-Breath** [comment]
请给出足够详细的能复现此问题的步骤

**Comment by GenMannnnnn** [comment]
目前重新构建一个新的资料夹解决问题，且无法重现这个错误。
同一时间建立的镜像伺服器也没有这个问题

**Comment by LeakDog** [comment]
我也触发这个问题了，可以把原文件夹内所有备份删除/转移的办法恢复游戏内qb的正常，目前没有找到其他解决办MCDReforged于Python 3.8.6环境中运行。
`游戏版本1.18.2问题遇到时日志如下:`
```
[MCDR] [2023-01-02 15:42:18] [QBM - restore/ERROR]: Fail to restore backup to slot 2, triggered by Player xing_hai_L
Traceback (most recent call last):
  File "plugins\[备份]QuickBackupM-v1.7.0.mcdr\quick_backup_multi\__init__.py", line 379, in _do_restore_backup
    shutil.rmtree(overwrite_backup_path)
  File "C:\Program Files\python\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\python\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\python\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\python\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Program Files\python\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] 拒绝访问。: './qb_multi\\overwrite\\world\\playerdata'
```

**Comment by yixino** [comment]
右键qb_multi点击属性-->安全 所有用户和组设置完全控制权限

**Comment by MoonShadow233** [comment]
把所有备份文件删了或者拿走，可以解决
