### ISSUE TITLE
无法正常备份

### ISSUE THREAD

**Issue by fly6516** [TISUnion/QuickBackupM#35]
控制台日志如下：
   [Server] [19:26:29] [Server thread/INFO]: Automatic saving is now disabled
[Server] [19:26:29] [Server thread/INFO]: Saving the game (this may take a moment!)
>
   [Server] [19:26:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [19:26:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [19:26:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [19:26:29] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [19:26:29] [Server thread/INFO]: Saved the game
>
   [MCDR] [19:26:29] [QBM - create/INFO] [quick_backup_multi]: copying ./server/world -> ./qb_multi/slot1/world
>
   [MCDR] [19:26:29] [QBM - create/ERROR]: [QBM] Error creating backup
Traceback (most recent call last):
  File "plugins/QuickBackupM-v1.6.0.mcdr/quick_backup_multi/__init__.py", line 267, in _create_backup
    copy_worlds(config.server_path, slot_path)
  File "plugins/QuickBackupM-v1.6.0.mcdr/quick_backup_multi/__init__.py", line 61, in copy_worlds
    shutil.copytree(src_path, dst_path, ignore=lambda path, files: set(filter(config.is_file_ignored, files)))
  File "/usr/lib64/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 504, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
  File "/usr/lib64/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 508, in _copytree
    copy_function(srcobj, dstname)
  File "/usr/lib64/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.9/site-packages/speedcopy/__init__.py", line 183, in copyfile
    fs_src_type = FilesystemInfo().filesystem(src.encode('utf-8'))
AttributeError: 'posix.DirEntry' object has no attribute 'encode'
>
   [Server] [19:26:29] [Server thread/INFO]: Automatic saving is now enabled
求一下解决方法谢谢

**Comment by HuiMengXunFeng** [comment]
我这边是排查半天发现FasterTransfer-v0.1.0插件会导致相同报错

**Comment by xunfengawa** [comment]
我这边是排查半天发现同时安装FasterTransfer-v0.1.0插件会导致这个报错

**Comment by fly6516** [comment]
确实是这个问题，禁用了就能用了
