### ISSUE TITLE
使用tar和tar.gz格式备份，显示备份失败

### ISSUE THREAD

**Issue by DavidBlackCN** [TISUnion/QuickBackupM#41]
mc=1.18.2 with Fabric
MCDR=2.7.2

pluginl ist：
QBM=1.8.0

log：
[MCDR] [2023-04-04 23:27:20] [QBM - create/INFO]: storing ./server\world -> ./qb_multi\slot1\backup.tar.gz
[MCDR] [2023-04-04 23:27:27] [QBM - create/ERROR]: [QBM] Error creating backup
Traceback (most recent call last):
  File "plugins\QuickBackupM-v1.8.0.mcdr\quick_backup_multi\__init__.py", line 367, in _create_backup
    copy_worlds(config.server_path, slot_path, CopyWorldIntent.backup)
  File "plugins\QuickBackupM-v1.8.0.mcdr\quick_backup_multi\__init__.py", line 130, in copy_worlds
    backup_file.add(src_path, arcname=world, filter=tar_filter)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\tarfile.py", line 1994, in add
    self.add(os.path.join(name, f), os.path.join(arcname, f),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\tarfile.py", line 1988, in add
    self.addfile(tarinfo, f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\tarfile.py", line 2016, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\tarfile.py", line 253, in copyfileobj
    buf = src.read(remainder)
PermissionError: [Errno 13] Permission denied

**Comment by Fallen-Breath** [comment]
如错误信息中所述，请检查文件权限。除此之外，对于 windows，请确保相关文件未被占用

**Comment by waynezhao12** [comment]
一样，用tar格式就没权限，管理员启动也一样

**Comment by DavidBlackCN** [comment]
已尝试使用管理员启动MCDR，且相关备份文件路径未被占用，仍如上所示（QBM update to 1.9.0）

**Comment by Fallen-Breath** [comment]
可以试试 https://github.com/TISUnion/QuickBackupM/commit/413b75f6a2902805f24100dae613c60f88869e59 https://github.com/TISUnion/QuickBackupM/actions/runs/5681668571 里的版本

这个提交修了 tar 模式下 `ignored_files` 无法正常工作的问题，导致 QBM 会读取 `session.lock` 这个总是爱造成权限不足的文件。如果依然不行，这开发版本也能打印出具体到文件的错误信息，能帮忙定位问题

**Comment by KleinQwQ** [comment]
这个正式版1.9还存在这个问题，然后您这个dev分支的包过期了 下载不了可以重发一边嘛？

**Comment by Fallen-Breath** [comment]
v1.10.0 已发布
