### ISSUE TITLE
TAR_GZ 模式下备份失败

### ISSUE THREAD

**Issue by z0z0r4** [TISUnion/QuickBackupM#55]
![image](https://github.com/TISUnion/QuickBackupM/assets/78744121/3e1a8095-ebd2-4a73-8bdd-49dd36035255)
```
Traceback (most recent call last):
  File "plugins\QuickBackupM-v1.9.0.mcdr\quick_backup_multi\__init__.py", line 408, in _create_backup
    copy_worlds(config.server_path, slot_path, CopyWorldIntent.backup)
  File "plugins\QuickBackupM-v1.9.0.mcdr\quick_backup_multi\__init__.py", line 156, in copy_worlds
    tar_path = os.path.join(dst, get_backup_file_name(backup_format))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\QuickBackupM-v1.9.0.mcdr\quick_backup_multi\__init__.py", line 82, in get_backup_file_name
    return backup_format.get_file_name('backup')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\QuickBackupM-v1.9.0.mcdr\quick_backup_multi\__init__.py", line 52, in get_file_name
    return base_name + self.value.suffix
                       ^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'suffix'
[MCDR] [15:10:04] [QBM - create/INFO]: [QBM] 备份失败，错误代码'tuple' object has no attribute 'suffix'
```

**Comment by z0z0r4** [comment]
debug 显示这个 `self.value.suffix` 是个元组

**Comment by Fallen-Breath** [comment]
已测试 v1.9.0、v1.10.0，均无法复现
