### ISSUE TITLE
在1.15.2版本中MCDR使用回档指令无法回档

### ISSUE THREAD

**Issue by Guaedlove** [TISUnion/QuickBackupM#6]
我在使用qb back并qb confirm后出现这样几行代码：
Wait for server to stop
Exception in thread on_info@QuickBackupM:
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./plugins/QuickBackupM.py", line 345, in on_info
    onServerInfo(server, info2)
  File "./plugins/QuickBackupM.py", line 331, in onServerInfo
    confirm_restore(server, info)
  File "./plugins/QuickBackupM.py", line 252, in confirm_restore
    while server.is_server_running():
AttributeError: 'ServerInterface' object has no attribute 'is_server_running'
后面接着就是正常服务器关闭后的文件保存，然后出现两行提示信息：
[MCDR] [14:35:29] [MainThread/INFO]: 等待服务端进程停止
[MCDR] [14:35:29] [MainThread/INFO]: 服务端进程返回代码: 0
最后就停在这不动弹了，请问怎么解决

**Comment by Fallen-Breath** [comment]
更新mcdr
